This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file ./thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (170 entries accepted, 0 rejected).
Sorting entries....done (1492 comparisons).
Generating output file thesis.acr....done (303 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
